version: 2
references:
  test_library: &test_library
    run:
      name: Test
      command: |
        pip install -r requirements-dev.txt
        nosetests

  test_defaults: &test_defaults
    parallelism: 1
    steps:
      - checkout
      - *test_library

jobs:
  test_python37:
    <<: *test_defaults
    docker:
      - image: python:3.7

  test_python36:
    <<: *test_defaults
    docker:
      - image: python:3.6

  test_python35:
    <<: *test_defaults
    docker:
      - image: python:3.5

  test_python34:
    <<: *test_defaults
    docker:
      - image: python:3.4

  test_python33:
    <<: *test_defaults
    docker:
      - image: python:3.3

  test_python27:
    <<: *test_defaults
    docker:
      - image: python:2.7


workflows:
  version: 2
  build:
    jobs:
      - test_python37
      - test_python36
      - test_python35
      - test_python34
      - test_python33
      - test_python27
